### ISSUE TITLE
Kotlin DSL by default for new Gradle builds

### ISSUE THREAD

**Issue by pioterj** [gradle/build-tool-roadmap#39]
Resolve the outstanding issues with Kotlin DSL, mostly about usability so it can be the default for new builds.

- Kotlin DSL can become the default in Android and other ecosystems

**Comment by pioterj** [comment]
See https://blog.gradle.org/kotlin-dsl-is-now-the-default-for-new-gradle-builds

**Comment by runningcode** [comment]
Is this complete?
