### ISSUE TITLE
Persistent Java compiler daemons

### ISSUE THREAD

**Issue by big-guy** [gradle/build-tool-roadmap#55]
When compiling Java, Groovy or Scala code, Gradle will start a compiler daemon. This worker can be reused by other projects during a single build, but at the end of the build, Gradle stops all compiler daemons.

In quick, incremental builds, the time spent to start the compiler daemon represents a large chunk of the overall build time. Since each build uses fresh JVMs, there is little opportunity for the JVM to warmup and run faster.

As a first step, we will enable persistent compiler daemons for Java by default. This should speed up builds that are dominated by the compiler daemon startup time. 

Groovy and Scala compiler daemons will be made persistent at a later time.
```[tasklist]
### Tasks
- [ ] https://github.com/gradle/gradle/issues/25425
```

**Comment by pioterj** [comment]
Released for macOS and Linux in Gradle 8.3. Windows support is coming in 8.4.
