### ISSUE TITLE
Fine grained problem details for the Tooling API

### ISSUE THREAD

**Issue by ljacomet** [gradle/build-tool-roadmap#68]
IDE clients will be able to query much more details about Gradle errors, exceptions and warnings starting with the Tooling API version 8.4 for build running with Gradle 8.4 and above.

Roadmap document: https://docs.google.com/document/d/1uA3x13eOERYUVgMiPBnZytlTxzJ4BkVvU_yw0V2Z5bI/edit#

**Comment by donat** [comment]
Superseded by #49.
